### ISSUE TITLE
Generated invalid URI

### ISSUE THREAD

**Issue by murad88** [Alterdata/RestSharp.Authenticators.Digest#1]
if baseURL="http://api.myhost.com" then generated an invalid URI ("http://api.myhost.com//values").

```
var client = new RestClient("http://api.myhost.com")
                {
                    Authenticator = new DigestAuthenticator("testusername", "testpassword")
                };
var request = new RestRequest("values", Method.POST);
var response = client.Execute(request);
```

Problem in `DigestAuthenticatorManager.GetDigestAuthHeader()`
I replaced `var uri = new Uri($"{host}{path}");` to `var uri = new Uri(host, path);` and is URI generated is valid.

**Comment by bernardbr** [comment]
Hello @murad88!

I made the change as your suggestion.

Version v1.0.2 was released on Nuget.

Thanks.
