### ISSUE TITLE
order of items in the WWW-Authenticate header

### ISSUE THREAD

**Issue by Steve0212a** [Alterdata/RestSharp.Authenticators.Digest#3]
I am new to digest authentication, but I am now trying to connect to a server using RestSharp and Digest authentication.  the same call works without issue in PostMan.

Using RestSharp.Authenticators.Digest, I was getting the error "Header not found: Digest realm".  After downloading your source code, I have found the issue.  You assume that the realm will be the first parameter after the scheme.  Therefore, your code is looking for "Digest realm" instead of just "realm".  However, the server I am connecting to does not have it first.  Here is a sample of the WWW-Authenticate header returned by the server I am trying to authenticate to.  

>        Digest qop="auth", realm="webserver@cpco", nonce="2389874222"

I have resolved this in your code with the following changes to DigestAuthenticatorManager:

>        private const string REALM = "realm"; // updated to remove Digest from the beginning of the string`
>
>        private static IDictionary<string, string> TransformHeaderToDictionary(string wwwAuthenticateHeader)
>        {
>            // added this to remove the scheme before processing the name/value pairs
>            if (wwwAuthenticateHeader.StartsWith("Digest "))
>                wwwAuthenticateHeader = wwwAuthenticateHeader.Substring(7);
>           ...

As I mentioned, I am new to digest authentication, so I am not sure if the that is the best way to remove the "Digest" scheme from the beginning of the header.

Could you please resolve this?

Thanks.

**Comment by RogerHardiman** [comment]
+1 for this from me.
I've implemented Digest Authentication in the SharpRTSP Project and on some commercial projects and the fix from @Steve0212a is the right thing to do.

Using a HikVision CCTV camera and the Header returned is
```
"Digest qop=\"auth\", realm=\"IP Camera(E4292)\", nonce=\"636164303a63666635303931343af64b139418d8de41bab6b2646477699b\", stale=\"FALSE\""
```

The RFC says the Header is "Digest<space>" followed by 1 or more comma separated parameters.
One of those parameters is called "realm" and it does not need to go first.

I had a look one of my open source digest parsers in the SharpRTSP project.
https://raw.githubusercontent.com/ngraziano/SharpRTSP/c499e463d3643d3283aad6146a904da344c7ff97/RTSP/Authentication.cs

I did the same sort of thing as @Steve0212a  has suggested, removed "Digest<space>"  before the Split().
```
  if (authentication_type == Type.Digest && authorization.StartsWith("Digest ")) {
                string value_str = authorization.Substring(7); // remove 'Digest '
                string[] values = value_str.Split(',');
```

So a +1 for this fix.

**Comment by bernardbr** [comment]
Hello @Steve0212a and @RogerHardiman! Sorry for the long time to respond to you.

I'll check these points and release a version as soon as possible.

Thanks for the feedback!

**Comment by bernardbr** [comment]
Version [1.1.0](https://www.nuget.org/packages/RestSharp.Authenticators.Digest/1.1.0) was released solving this issue.
This version is under validation now.

**Comment by RogerHardiman** [comment]
Many thanks for looking into this

**Comment by Steve0212a** [comment]
Thank you for the fix!
