### ISSUE TITLE
System.TypeLoadException error after updating RestSharp to 107.1.2

### ISSUE THREAD

**Issue by Codimon159** [Alterdata/RestSharp.Authenticators.Digest#6]
Hey there,
i get the following error when i try to compile the example code. I think its related to the last RestSharp Update:

System.TypeLoadException: "Method 'Authenticate' in type 'RestSharp.Authenticators.Digest.DigestAuthenticator' from assembly 'RestSharp.Authenticators.Digest, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation."

Any hint how to solve this? Thanks

**Comment by bernardbr** [comment]
Hello @Codimon159, I just released version 1.3.0 with compatibility with the new version of RestSharp.

**Comment by Codimon159** [comment]
Bernardo Esb?rard ***@***.***> schrieb am Mi. 2. Feb. 2022 um 21:35:
Hello @Codimon159, I just released version 1.3.0 with compatibility with the new version of RestSharp.

?Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you were mentioned.Message ID: ***@***.***>
Thanks for coming back at me and for your work of course.I will try the Update. Cheers Timon
