### ISSUE TITLE
QOP not surrounded by " not detected and throws exception

### ISSUE THREAD

**Issue by alexandre-marquis** [Alterdata/RestSharp.Authenticators.Digest#8]
I have encountered a source where the qop was not surrounded by `"` like so
`Digest realm="xxx", nonce="9b3d8629ab0d40abaf9d7aad1eaf9e1a", opaque="3d4d2d0ef83f4272b5b4064746805471", stale=false, algorithm=MD5, qop=auth`

When encountered, the regex sees that there's a qop, but the value is empty because it's expected to be surrounded by `"` and then throws an exception.
I fixed the issue on my side by detecting the header just before the regex and adding the `"` in [DigestHeader.cs](https://github.com/bernardbr/RestSharp.Authenticators.Digest/blob/b734115c081ae8700550da0487fd652f6f201cc2/src/DigestAuthenticator/DigestHeader.cs#L27)
```csharp
if (authenticateHeader.Contains("qop=auth"))
{
    authenticateHeader = authenticateHeader.Replace("qop=auth", "qop=\"auth\"");
}
```

**Comment by bernardbr** [comment]
Hello @alexandre-marquis, sorry about the delay. I fix your issue on version v1.4.0.
