### ISSUE TITLE
[Bug] Stopped working on RestSharp Ver. 109.0.0 and higher.

### ISSUE THREAD

**Issue by lohchab** [Alterdata/RestSharp.Authenticators.Digest#9]
This has stopped working since RestSharp Ver. [109.0.0](https://www.nuget.org/packages/RestSharp/109.0.0)

In these versions the RestSharp allows to only define the Authentication in the RestClientOptions Object. Despite everything properly configured the RestSharp.Authenticators.Digest throws an exception. You can try running in your environment to reproduce.

**Comment by CarlAreDHopen-eaton** [comment]
I'm seeing the same issue, it seems to be **BuildUri** in **RestClient.cs** is now **internal**, this was changed in pull request 1963 (https://github.com/restsharp/RestSharp/pull/1963)

**Comment by bernardbr** [comment]
Hi! I'll check that. Thanks for the report on this issue.

**Comment by krunal-jethva-tark** [comment]
updating from 18.0.3 -> 19.0.1

I had similar issue, according to the documentation here - https://restsharp.dev/authenticators.html#basic-authentication

![image](https://user-images.githubusercontent.com/104830964/229423050-1527f196-d582-462a-b4ed-1dedeca3eb28.png)

But when I do that it says `Authenticator` is read-only. 
Maybe there is another way to set in this update, then please update the documents.

**Comment by lohchab** [comment]
> updating from 18.0.3 -> 19.0.1
> 
> I had similar issue, according to the documentation here - https://restsharp.dev/authenticators.html#basic-authentication
> 
> ![image](https://user-images.githubusercontent.com/104830964/229423050-1527f196-d582-462a-b4ed-1dedeca3eb28.png)
> 
> But when I do that it says `Authenticator` is read-only. Maybe there is another way to set in this update, then please update the documents.

You set that now through the RestClientOptions object and passing that to the RestClient Instance.

Example.

```
var options = new RestClientOptions("https://example.com")
{
  Authenticator = new HttpBasicAuthenticator("username", "password"),
};

var client = new RestClient(options);
```

**Comment by krunal-jethva-tark** [comment]
> > updating from 18.0.3 -> 19.0.1
> > I had similar issue, according to the documentation here - https://restsharp.dev/authenticators.html#basic-authentication
> > ![image](https://user-images.githubusercontent.com/104830964/229423050-1527f196-d582-462a-b4ed-1dedeca3eb28.png)
> > But when I do that it says `Authenticator` is read-only. Maybe there is another way to set in this update, then please update the documents.
> 
> You set that now through the RestClientOptions object and passing that to the RestClient Instance.
> 
> Example.
> 
> `var options = new RestClientOptions("https://example.com") { Authenticator = new HttpBasicAuthenticator("username", "password"), };
> 
> var client = new RestClient(options);`

for code try this ```

**Comment by panos-stavrianos** [comment]
Is there a workaround for the BuildUri?
```
Method RestSharp.RestClient.BuildUri(RestSharp.RestRequest)
is inaccessible from method
RestSharp.Authenticators.Digest.DigestAuthenticator+<Authenticate>d__8.MoveNext()
```

In the [migration guide](https://restsharp.dev/v107/#restclient-and-options) says that it's an extension now 

BuildUri(IRestRequest request) | Extension
-- | --

**Comment by bernardbr** [comment]
@panos-stavrianos I've fix some bugs, and included an real integration tests for the extensions. Sorry about the delay.

@lohchab sorry about the delay.

**Comment by Cosmas47** [comment]
4/6/26 - This issue appears to have resurfaced again in 114.0 ?

**Comment by bernardbr** [comment]
> 4/6/26 - This issue appears to have resurfaced again in 114.0 ?

Apparently so, from what I saw in the RestSharp changelog, there were changes that broke backward compatibility between versions 112 and 114. I'll check if I can generate a new version with the adjustments.

**Comment by bernardbr** [comment]
> 4/6/26 - This issue appears to have resurfaced again in 114.0 ?

Closing, the release is deployed.
[v3.0.0](https://www.nuget.org/packages/RestSharp.Authenticators.Digest/3.0.0)
